### PR TITLE
Removed unneeded persisting of testresult requests

### PR DESCRIPTION
**Pull request by predic8**
The test-restults server stores data that is not needed. From my perspective it is not much of an issue but maybe you want to fix this to provide the best privacy possible.

When the app requests a test result before the result is send from the laboratory to the test results server the id (hashed GUID) and the date is saved with state pending. It is not needed to store that somebody has asked for the result.

With the fix the server works as before and the tests are passing.

### CODE REVIEW

**Comment by predic8** [comment]
@daniel-eder I would fix that issue soon to provide maximum privacy. IMHO it is not so critical but others might see that differently.

**Comment by daniel-eder** [comment]
Hi @predic8, thank you creating the PR and for bumping it.! We're still actively reviewing and accepting/implementing all the open issues and PRs, however, developer resources are currently mainly allocated to input from the RKI and BSI. 

That said, I will request a review of your PR to evaluate how to prioritize it.

**Comment by predic8** [comment]
Almost a year to review a pull request concerning a privacy issue.

**Comment by ascheibal** [comment]
Hi @predic8, your PR looks indeed reasonable. We did not investigate on possible side effects so far, that's why it is not approved. As dataflows and -models where confirmed during threat modeling and data privacy process we have to agree upon that, too.
Thanks for contribution, nevertheless.

**Pull request closed without merging**
